### ISSUE TITLE
formato para GitBook

### ISSUE THREAD

**Issue by carlosdelfino** [gomex/docker-para-desenvolvedores#57]
Olá Rafael.

Você tem intenção de migrar este livro para algum formato tipo gitbook?

Eu sempre que vou ler algum livro aberto tento migrar o formato para o GitBook assim me ajuda a manter um padrão de uso.

Caso me permita nas próximas semanas poderei fazer isso.

Abraços.

**Comment by gomex** [comment]
Pode ficar a vontade :) Manda um PR

**Comment by somatorio** [comment]
já que o PR foi fechado, estou fechando essa issue
