### ISSUE TITLE
Onde encontro o livro impresso

### ISSUE THREAD

**Issue by fredpolicarpo** [gomex/docker-para-desenvolvedores#71]
Olá Rafael,

Onde posso comprar uma versão impressa do seu livro?

**Comment by wilcorrea** [comment]
Opa, não sou o Rafael, mas participei desse projeto aqui https://www.catarse.me/versao_impressa_do_livro_docker_para_desenvolvedores_c403 e agora sei que é possível adquirir uma cópia aqui https://www.9bravos.com.br/loja/produto/docker-para-desenvolvedores/

**Comment by fredpolicarpo** [comment]
Ah sim.

Desculpe o engano e obrigado pela informação!

Abraço
